export const mockRepositories = [
  {
    id: 1,
    name: "awesome-react-components",
    description:
      "A curated list of awesome React components and libraries for building modern web applications.",
    language: "TypeScript",
    stars: 15420,
    forks: 2341,
    watchers: 892,
    updatedAt: "2024-01-15",
    topics: ["react", "components", "ui", "frontend"],
    isPrivate: false,
  },
  {
    id: 2,
    name: "nextjs-dashboard",
    description:
      "A modern dashboard built with Next.js 14, featuring server components and advanced routing.",
    language: "JavaScript",
    stars: 8765,
    forks: 1234,
    watchers: 456,
    updatedAt: "2024-01-12",
    topics: ["nextjs", "dashboard", "react", "tailwind"],
    isPrivate: false,
  },
  {
    id: 3,
    name: "python-ml-toolkit",
    description:
      "Machine learning toolkit with pre-built models and utilities for data scientists.",
    language: "Python",
    stars: 12890,
    forks: 3456,
    watchers: 789,
    updatedAt: "2024-01-10",
    topics: ["python", "machine-learning", "ai", "data-science"],
    isPrivate: false,
  },
  {
    id: 4,
    name: "vue-admin-panel",
    description:
      "Professional admin panel template built with Vue 3 and Composition API.",
    language: "Vue",
    stars: 6543,
    forks: 987,
    watchers: 234,
    updatedAt: "2024-01-08",
    topics: ["vue", "admin", "template", "composition-api"],
    isPrivate: true,
  },
  {
    id: 5,
    name: "rust-web-server",
    description:
      "High-performance web server written in Rust with async/await support.",
    language: "Rust",
    stars: 9876,
    forks: 1567,
    watchers: 345,
    updatedAt: "2024-01-05",
    topics: ["rust", "web-server", "async", "performance"],
    isPrivate: false,
  },
  {
    id: 6,
    name: "go-microservices",
    description:
      "Microservices architecture example using Go, Docker, and Kubernetes.",
    language: "Go",
    stars: 11234,
    forks: 2890,
    watchers: 567,
    updatedAt: "2024-01-03",
    topics: ["go", "microservices", "docker", "kubernetes"],
    isPrivate: false,
  },
];
